### ISSUE TITLE
missing docstring_to_markdown package

### ISSUE THREAD

**Issue by jeffworne** [sublimelsp/LSP-pylsp#131]
Hi,

I recently started having the issue shown below, and I'm not sure how to troubleshoot further.

# Troubleshooting: LSP-pylsp
## Version
 - LSP: 1.25.0
 - Sublime Text: 4152
## Server Test Run
 - exit code: 1
 - output
```
Traceback (most recent call last):
  File "C:\local\python38\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\local\python38\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\local\st3\Data\Package Storage\LSP-pylsp\Scripts\pylsp.exe\__main__.py", line 5, in <module>
  File "c:\local\st3\data\package storage\lsp-pylsp\lib\site-packages\pylsp\__main__.py", line 15, in <module>
    from .python_lsp import (PythonLSPServer, start_io_lang_server,
  File "c:\local\st3\data\package storage\lsp-pylsp\lib\site-packages\pylsp\python_lsp.py", line 15, in <module>
    from . import lsp, _utils, uris
  File "c:\local\st3\data\package storage\lsp-pylsp\lib\site-packages\pylsp\_utils.py", line 13, in <module>
    import docstring_to_markdown
ModuleNotFoundError: No module named 'docstring_to_markdown'
```
## Server Configuration
 - command
```json
[
  "$server_path"
]
```
 - shell command
```sh
"C:\local\st3\Data\Package Storage\LSP-pylsp\Scripts\pylsp.exe"
```
 - selector
```
source.python
```
 - priority_selector
```
(source.python)
```
 - init_options
```json
{}
```
 - settings
```json
{
  "pylsp": {
    "configurationSources": [
      "pycodestyle"
    ], 
    "plugins": {
      "autopep8": {
        "enabled": true
      }, 
      "flake8": {
        "config": null, 
        "enabled": false, 
        "exclude": null, 
        "executable": "flake8", 
        "filename": null, 
        "hangClosing": null, 
        "ignore": null, 
        "maxLineLength": 120, 
        "perFileIgnores": null, 
        "select": null
      }, 
      "jedi": {
        "auto_import_modules": [
          "numpy"
        ], 
        "env_vars": null, 
        "environment": null, 
        "extra_paths": [
          "$sublime_py_files_dir", 
          "$packages"
        ]
      }, 
      "jedi_completion": {
        "cache_for": [
          "pandas", 
          "numpy", 
          "tensorflow", 
          "matplotlib"
        ], 
        "eager": false, 
        "enabled": false, 
        "fuzzy": true, 
        "include_class_objects": false, 
        "include_function_objects": false, 
        "include_params": true, 
        "resolve_at_most": 25
      }, 
      "jedi_definition": {
        "enabled": false, 
        "follow_builtin_imports": true, 
        "follow_imports": true
      }, 
      "jedi_hover": {
        "enabled": false
      }, 
      "jedi_references": {
        "enabled": false
      }, 
      "jedi_signature_help": {
        "enabled": false
      }, 
      "jedi_symbols": {
        "all_scopes": true, 
        "enabled": false, 
        "include_import_symbols": true
      }, 
      "mccabe": {
        "enabled": true, 
        "threshold": 15
      }, 
      "preload": {
        "enabled": true, 
        "modules": null
      }, 
      "pycodestyle": {
        "aggressive": 1, 
        "enabled": true, 
        "exclude": null, 
        "filename": null, 
        "hangClosing": null, 
        "ignore": null, 
        "maxLineLength": 120, 
        "select": null
      }, 
      "pydocstyle": {
        "addIgnore": null, 
        "addSelect": null, 
        "convention": null, 
        "enabled": false, 
        "ignore": null, 
        "match": "(?!test_).*\\.py", 
        "matchDir": "[^\\.].*", 
        "select": null
      }, 
      "pyflakes": {
        "enabled": false
      }, 
      "pylint": {
        "args": null, 
        "enabled": false, 
        "executable": ""
      }, 
      "pyls_isort": {
        "enabled": true
      }, 
      "pylsp_black": {
        "cache_config": false, 
        "enabled": false, 
        "line_length": 120, 
        "preview": false
      }, 
      "pylsp_mypy": {
        "dmypy": false, 
        "enabled": false, 
        "live_mode": false, 
        "strict": false
      }, 
      "rope_completion": {
        "eager": false, 
        "enabled": false
      }, 
      "yapf": {
        "enabled": false
      }
    }, 
    "rope": {
      "extensionModules": null, 
      "ropeFolder": null
    }
  }
}
```
 - env
```json
{
  "HTTPS_PROXY": "http://x.x.x.x:xx", 
  "HTTP_PROXY": "http://x.x.x.x:xx", 
  "PATH": "C:\\local\\st3\\Data\\Package Storage\\LSP-pylsp\\Scripts;", 
  "PYTHONPATH": "${sublime_py_files_dir}${pathsep}${packages}"
}
```

## Active view
 - File name
```
Z:\home\...
```
 - Settings
```json
{
  "auto_complete_selector": "meta.tag, source - comment - string.quoted.double.block - string.quoted.single.block - string.unquoted.heredoc", 
  "lsp_active": true, 
  "syntax": "Packages/MagicPython/grammars/MagicPython.tmLanguage"
}
```
 - base scope
```
source.python
```

## Project / Workspace
 - folders
```json
[
  "Z:\\home\\..."
]
```
 - is project: True
 - project data:
```json
{
  "folders": [
    {
      "path": "."
    }
  ]
}
```

## LSP configuration

<not found>
## System PATH
 - C:\Program Files (x86)\Common Files\Oracle\Java\javapath
 - C:\WINDOWS\system32
 - C:\WINDOWS
 - C:\WINDOWS\System32\Wbem
 - C:\WINDOWS\System32\WindowsPowerShell\v1.0\
 - C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
 - C:\WINDOWS\system32
 - C:\WINDOWS
 - C:\WINDOWS\System32\Wbem
 - C:\WINDOWS\System32\WindowsPowerShell\v1.0\
 - C:\WINDOWS\System32\OpenSSH\
 - C:\local\node-v16.13.1
 - C:\local\python38\Scripts\
 - C:\local\python38\
 - C:\Users\jworne\AppData\Local\Programs\Python\Launcher\
 - C:\Python37\Scripts\
 - C:\Python37\
 - C:\local\python-3.7
 - C:\local\Sublime Text Build 3083 x64
 - C:\Users\jworne\AppData\Local\Microsoft\WindowsApps
 - C:\Program Files (x86)\Common Files\Oracle\Java\javapath
 - C:\WINDOWS\system32
 - C:\WINDOWS
 - C:\WINDOWS\System32\Wbem
 - C:\WINDOWS\System32\WindowsPowerShell\v1.0\
 - C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
 - C:\WINDOWS\system32
 - C:\WINDOWS
 - C:\WINDOWS\System32\Wbem
 - C:\WINDOWS\System32\WindowsPowerShell\v1.0\
 - C:\WINDOWS\System32\OpenSSH\
 - 
 - C:\Users\jworne\AppData\Local\Programs\Microsoft VS Code\bin

**Comment by rchl** [comment]
What's the contents of the `c:\local\st3\data\package storage\lsp-pylsp\lib\site-packages\docstring_to_markdown` directory?

**Comment by rchl** [comment]
Please try the suggestion above.
