### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by UmeSiyah** [sublimelsp/LSP-pylsp#135]
Hello,

I can't find a way to run LSP-pylsp after installing the package I get this error :

`FileNotFoundError: [Errno 2] No such file or directory: '~/.cache/sublime-text-3/Package Storage/LSP-pylsp/bin/pip'`

I have tried creating the folder and restart but it looks like something is removing it.

Can anyone help me to figure this out ?

P.S. : I have LSP-pyright running perfectly

**EDIT** : Adding the traceback :
```
Traceback (most recent call last):
  File "~/.config/sublime-text-3/Installed Packages/LSP.sublime-package/plugin/core/windows.py", line 245, in start_async
    plugin_class.install_or_update()
  File "~/.config/sublime-text-3/Packages/lsp_utils/st3/lsp_utils/_client_handler/abstract_plugin.py", line 109, in install_or_update
    server.install_or_update()
  File "~/.config/sublime-text-3/Packages/lsp_utils/st3/lsp_utils/server_pip_resource.py", line 100, in install_or_update
    self.run(self.pip_binary(), 'install', '-r', dest_requirements_txt_path, '--disable-pip-version-check')
  File "~/.config/sublime-text-3/Packages/lsp_utils/st3/lsp_utils/server_pip_resource.py", line 33, in run
    output, error = run_command_sync(list(args), cwd=cwd)
  File "~/.config/sublime-text-3/Packages/lsp_utils/st3/lsp_utils/helpers.py", line 40, in run_command_sync
    args, cwd=cwd, shell=shell, stderr=subprocess.STDOUT, env=env, startupinfo=startupinfo)
  File "./python3.3/subprocess.py", line 576, in check_output
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1452, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: '~/.cache/sublime-text-3/Package Storage/LSP-pylsp/bin/pip'
```

**Comment by rchl** [comment]
Is there more relevant information in the Sublime Text console? Restart ST, wait for the error to trigger and provide all information from the ST console.

**Comment by UmeSiyah** [comment]
> Is there more relevant information in the Sublime Text console? Restart ST, wait for the error to trigger and provide all information from the ST console.

 I should have post it in the first post.
```
Traceback (most recent call last):
  File "~/.config/sublime-text-3/Installed Packages/LSP.sublime-package/plugin/core/windows.py", line 245, in start_async
    plugin_class.install_or_update()
  File "~/.config/sublime-text-3/Packages/lsp_utils/st3/lsp_utils/_client_handler/abstract_plugin.py", line 109, in install_or_update
    server.install_or_update()
  File "~/.config/sublime-text-3/Packages/lsp_utils/st3/lsp_utils/server_pip_resource.py", line 100, in install_or_update
    self.run(self.pip_binary(), 'install', '-r', dest_requirements_txt_path, '--disable-pip-version-check')
  File "~/.config/sublime-text-3/Packages/lsp_utils/st3/lsp_utils/server_pip_resource.py", line 33, in run
    output, error = run_command_sync(list(args), cwd=cwd)
  File "~/.config/sublime-text-3/Packages/lsp_utils/st3/lsp_utils/helpers.py", line 40, in run_command_sync
    args, cwd=cwd, shell=shell, stderr=subprocess.STDOUT, env=env, startupinfo=startupinfo)
  File "./python3.3/subprocess.py", line 576, in check_output
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1452, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: '~/.cache/sublime-text-3/Package Storage/LSP-pylsp/bin/pip'
```

I replaced the head of paths by '~'

**Comment by rchl** [comment]
Looks like you need to install pip (https://www.google.com/search?q=install+pip+windows).

Though when installing Python with the official installer, I believe it should come with pip already so you might just try the official installer first.

**Comment by UmeSiyah** [comment]
I have pip and python installed ! In a custom way... and yes `pip` return nothing but `pip3` works, for some reason I cannot install pip or make an aliase for now.
There is a way to tel to LSP-pylsp where is the pip to use ? Like for the [/usr/local/bin](https://github.com/sublimelsp/LSP-pylsp#python-binary) ?

**Comment by rchl** [comment]
The code first creates a virtual environment by calling `python -m venv` and then expects to find `pip` in that environment.

What files are present inside of `~/.cache/sublime-text-3/Package Storage/LSP-pylsp/bin/`? If there is `pip3` then maybe we can change the code here to use either `pip3` or `pip`.

**Comment by UmeSiyah** [comment]
There is no folder `~/.cache/sublime-text-3/Package Storage/LSP-pylsp/bin/` I tried to make a link to pip -> pip3 in `~/.cache/sublime-text-3/Package Storage/LSP-pylsp/bin/` which I created, but after starting `pylsp` the folder is gone and I have the same error

**Comment by rchl** [comment]
I think we clean/delete that directory on error so that's why you can't see it.

You can run `python -m venv testdir` in some directory and check `testdir/bin`.

**Comment by UmeSiyah** [comment]
I tried :
```
python -m venv testdir
/usr/bin/python: No module named venv```

But 
`python3 -m venv testdir` works : 
```
Oct 10 10:04 activate
Oct 10 10:04 activate.csh
Oct 10 10:04 activate.fish
Oct 10 10:04 easy_install
Oct 10 10:04 easy_install-3.6
Oct 10 10:04 pip3
Oct 10 10:04 pip
Oct 10 10:04 pip3.6
Oct 10 10:04 python -> python3
Oct 10 10:04 python3 -> /usr/bin/python3
```

**Comment by rchl** [comment]
You can try some more advanced debugging.

1. Open `~/.config/sublime-text-3/Packages/lsp_utils/st3/lsp_utils/server_pip_resource.py` in ST and remove [this line](https://github.com/sublimelsp/lsp_utils/blob/1cf45dcf7772c9f63988d5c0876911acff7b6895/st3/lsp_utils/server_pip_resource.py#L104-L104)
2. Restart ST and wait until the error shows up again
3. Check and list the contents of the `~/.cache/sublime-text-3/Package Storage/LSP-pylsp/bin/` directory.

**Comment by UmeSiyah** [comment]
I try what you say and : 

- The contains in the the `~/.cache/sublime-text-3/Package Storage/LSP-pylsp/bin/`
```tree
.
├── activate
├── activate.csh
├── activate.fish
├── easy_install
├── easy_install-3.7
├── pip
├── pip3
├── pip3.7
├── python -> /u/td/WS/workspaceSB/.vpyenv/newsbpy/bin/python
└── python3 -> python
```

- And the new error
```
Unable to start subprocess for LSP-pylsp
Traceback (most recent call last):
  File "~/.config/sublime-text-3/Installed Packages/LSP.sublime-package/plugin/core/windows.py", line 245, in start_async
    plugin_class.install_or_update()
  File "~/.config/sublime-text-3/Packages/lsp_utils/st3/lsp_utils/_client_handler/abstract_plugin.py", line 109, in install_or_update
    server.install_or_update()
  File "~/.config/sublime-text-3/Packages/lsp_utils/st3/lsp_utils/server_pip_resource.py", line 100, in install_or_update
    ResourcePath(self._requirements_path).copy(dest_requirements_txt_path)
  File "~/.config/sublime-text-3/Packages/lsp_utils/st3/lsp_utils/server_pip_resource.py", line 35, in run
    if error:
Exception: ERROR: Could not find a version that satisfies the requirement mypy==1.6.0 (from -r ~/.cache/sublime-text-3/Package Storage/LSP-pylsp/requirements.txt (line 1)) (from versions: 0.1, 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.20, 0.21, 0.221, 0.222, 0.223, 0.224, 0.225, 0.226, 0.227, 0.228, 0.229, 0.230, 0.231, 0.232, 0.233, 0.234, 0.235, 0.236, 0.237, 0.238, 0.239, 0.240, 0.241, 0.250, 0.251, 0.252, 0.253, 0.254, 0.255, 0.256, 0.470, 0.471, 0.501, 0.510, 0.511, 0.520, 0.521, 0.530, 0.540, 0.550, 0.560, 0.570, 0.580, 0.590, 0.600, 0.610, 0.620, 0.630, 0.641, 0.650, 0.660, 0.670, 0.700, 0.701, 0.710, 0.711, 0.720, 0.730, 0.740, 0.750, 0.760, 0.761, 0.770, 0.780, 0.781, 0.782, 0.790, 0.800, 0.812, 0.900, 0.901, 0.902, 0.910, 0.920, 0.921, 0.930, 0.931, 0.940, 0.941, 0.942, 0.950, 0.960, 0.961, 0.971, 0.981, 0.982, 0.990, 0.991, 1.0.0, 1.0.1, 1.1.1, 1.2.0, 1.3.0, 1.4.0, 1.4.1)
ERROR: No matching distribution found for mypy==1.6.0 (from -r ~/.cache/sublime-text-3/Package Storage/LSP-pylsp/requirements.txt (line 1))```

I think it use the wrong version of the python installed on my machine.

Thank your for help :)

**Comment by rchl** [comment]
Mypy 1.6.0 requires 3.8 minimum

**Comment by UmeSiyah** [comment]
And we are under python 3.7 in my studio... 

Thanks for your time !
