### ISSUE TITLE
ERROR: No matching distribution found for mypy==1.8.0

### ISSUE THREAD

**Issue by dongguaguaguagua** [sublimelsp/LSP-pylsp#161]
```
Unable to start subprocess for LSP-pylsp
Traceback (most recent call last):
  File "/Users/huzongyao/Library/Application Support/Sublime Text/Lib/python33/lsp_utils/server_pip_resource.py", line 103, in install_or_update
    self.run(self.pip_binary(), 'install', '-r', dest_requirements_txt_path, '--disable-pip-version-check')
  File "/Users/huzongyao/Library/Application Support/Sublime Text/Lib/python33/lsp_utils/server_pip_resource.py", line 35, in run
    raise Exception(error)
Exception: WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/mypy/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/mypy/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/mypy/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/mypy/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/mypy/
Could not fetch URL https://pypi.org/simple/mypy/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/mypy/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
ERROR: Could not find a version that satisfies the requirement mypy==1.8.0 (from versions: none)
ERROR: No matching distribution found for mypy==1.8.0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/huzongyao/Library/Application Support/Sublime Text/Installed Packages/LSP.sublime-package/plugin/core/windows.py", line 252, in start_async
    plugin_class.install_or_update()
  File "/Users/huzongyao/Library/Application Support/Sublime Text/Lib/python33/lsp_utils/_client_handler/abstract_plugin.py", line 109, in install_or_update
    server.install_or_update()
  File "/Users/huzongyao/Library/Application Support/Sublime Text/Lib/python33/lsp_utils/server_pip_resource.py", line 108, in install_or_update
    raise Exception('Error installing the server:\n{}'.format(error))
Exception: Error installing the server:
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/mypy/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/mypy/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/mypy/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/mypy/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/mypy/
Could not fetch URL https://pypi.org/simple/mypy/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/mypy/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
ERROR: Could not find a version that satisfies the requirement mypy==1.8.0 (from versions: none)
ERROR: No matching distribution found for mypy==1.8.0
```

- MacOS
- Sublime Build 4169
- Latest lsp-pylsp

Pylsp was installing and then **crashed** when I tried to `enable lsp-pylsp in project`. Please tell me how to fix it!

**Comment by rchl** [comment]
> Could not fetch URL https://pypi.org/simple/mypy/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/mypy/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping

Might be some other ST package messing with SSL configuration. You would have to find out which one causes the issue.
