### ISSUE TITLE
pyls exited with status code -32602

### ISSUE THREAD

**Issue by thep0y** [sublimelsp/LSP-pylsp#22]
I'm using ST4(4101) on macOS 11.2.3.
My project settings:
```json
{
	"folders": [
		{
			"path": ".",
		}
	],
	"settings": {
		"LSP": {
			"pyls": {
				"enabled": true,
				"env": {
					"PYTHONPATH": "/Users/thepoy/venvs/spider/lib/python3.8/site-packages",
				},
				"command": [
					"/Users/thepoy/Library/Python/3.8/bin/pyls"
				],
			},
		},
	},
}
```
`pyls` can't work.
The log in console:
```shell
Traceback (most recent call last):
  File "/Users/thepoy/Library/Application Support/Sublime Text/Installed Packages/LSP.sublime-package/plugin/core/transports.py", line 137, in invoke
  File "/Users/thepoy/Library/Application Support/Sublime Text/Installed Packages/LSP.sublime-package/plugin/core/sessions.py", line 1259, in on_transport_close
  File "/Users/thepoy/Library/Application Support/Sublime Text/Installed Packages/LSP.sublime-package/plugin/core/windows.py", line 433, in on_post_exit_async
  File "./python3.3/_weakrefset.py", line 60, in __iter__
RuntimeError: Set changed size during iteration
```

**Comment by rchl** [comment]
I guess you've got this sorted out judging from your later bug report.
