### ISSUE TITLE
LSP won't load in sublimetext 4121

### ISSUE THREAD

**Issue by julianebeli** [sublimelsp/LSP-pylsp#54]
I'm seeing this message in the console
```
Traceback (most recent call last):
  File "/opt/sublime_text/Lib/python33/sublime_plugin.py", line 308, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text/Lib/python33/sublime_plugin.py", line 1692, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/home/julian/.config/sublime-text-3/Installed Packages/LSP-pylsp.sublime-package/plugin.py", line 1, in <module>
ImportError: No module named 'LSP'
```
My machine is linux mint debian edition LMDE4

I don't know anything about how ST loads packages, but nothing else is creating an error
.config/sublime-text-3/Installed Packages/LSP-pylsp.sublime-package/plugin.py
is not a file
.config/sublime-text-3/Installed Packages/LSP-pylsp.sublime-package
is an archive with plugin.py in it.

Thanks

**Comment by rwols** [comment]
Did you install the “LSP” package as well?

**Comment by julianebeli** [comment]
I have now!
And the error is gone.
I kind of expected that the pylsp plugin would have asked for LSP to be there?
Or just yanked it of its own accord.
Its a pretty fundamental dependency.
Anyway, enough of me pretending I'm not to blame!
Thanks
